Changed postinst to remove files it wants to create so that bad uninstalls don't mess up future reinstalls unnecessarily.

diff --git a/postinst b/postinst
--- a/postinst
+++ b/postinst
@@ -1,122 +1,69 @@
 #!/bin/sh
 APP_DIR=/var/usr/palm/applications/org.webosinternals.virtual-keyboard
-PATCH_NAME=add-onscreen-keyboard.patch
-DBG_ECHO=echo
-PACKAGE_REMOVE='ipkg -o /var remove $PATCH_NAME'
-FILE_LIST=`/var/usr/bin/diffstat -p1 -l $APP_DIR/$PATCH_NAME`
-IPKG_INFO_DIR=/usr/lib/ipkg/info
-PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches
-
-do_failure() {
-  $DBG_ECHO $PACKAGE_REMOVE
-  exit 1
-}
-
-/var/usr/bin/patch -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME || do_failure
-if [ ! -d $PATCH_CONTROL_DIR ]
-then
-  rm -rf $PATCH_CONTROL_DIR
-  mkdir $PATCH_CONTROL_DIR || do_failure
-fi
-
-if [ ! -e $PATCH_CONTROL_DIR/backups ]
-then
-  touch $PATCH_CONTROL_DIR/backups || do_failure
-fi
-
-if [ ! -e $PATCH_CONTROL_DIR/packages ]
-then
-  touch $PATCH_CONTROL_DIR/packages || do_failure
-fi
-
-rm -f $PATCH_CONTROL_DIR/tmp
-touch $PATCH_CONTROL_DIR/tmp || do_failure
-
-for i in $FILE_LIST
-do
-  file=/$i
-  if [ `grep -l $file $IPKG_INFO_DIR/*.md5sums | wc -l` -gt 1 ]
-  then
-    echo "ERROR: File found in multiple packages: $file"
-    do_failure
-  fi
-  
-  in_list="no"
-  for j in `cat $PATCH_CONTROL_DIR/backups`
-  do
-    if [ "$file" = "$j" ]
-    then
-      in_list="yes"
-      break
-    fi
-  done
-
-  if [ "$in_list" = "yes" ]
-  then
-    echo "VERIFY BACKUP"
-  else
-    expected=`grep -h $file $IPKG_INFO_DIR/*.md5sums | awk '{print $1}'`
-    echo "file $file"
-    if [ "$expected" != "" ]
-    then
-      calculated=`md5sum $file | awk '{print $1}'`
-      if [ "$expected" != "$calculated" ]
-      then
-        echo "ERROR: MD5SUMS do not match"
-        echo "       expected: $expected"
-        echo "       calculated: $calculated"
-        do_failure
-      else
-        echo "NOTE: Palm md5sum found: $expected $file"
-      fi
-    fi
-
-    if [ -e $file.webosinternals.orig ]
-    then
-      orig_md5sum=`md5sum $file.webosinternals.orig | awk '{print $1}'`
-      file_md5sum=`md5sum $file | awk '{print $1}'`
-      if [ "$orig_md5sum" != "$file_md5sum" ]
-      then
-        echo "ERROR: Existing backup file not in list, but md5sums do not match"
-        echo "       backup md5sum: $orig_md5sum"
-        echo "       current md5sum: $file_md5sum"
-        do_failure
-      fi
-    fi
-
-    echo $file >> $PATCH_CONTROL_DIR/tmp
-  fi
-done
-
-if [ -e $PATCH_CONTROL_DIR/$PATCH_NAME ]
-then
-  echo "ERROR: Patch already installed?"
-  do_failure
-fi
-
-for i in `cat $PATCH_CONTROL_DIR/tmp`
-do
-  if [ ! -e $i ]
-  then
-    touch $i.webosinternals.orig
-  else
-    cp $i $i.webosinternals.orig
-  fi
-
-  echo $i >> $PATCH_CONTROL_DIR/backups
-done
-
-basename $APP_DIR >> $PATCH_CONTROL_DIR/packages
-
-cp $APP_DIR/$PATCH_NAME $PATCH_CONTROL_DIR/$PATCH_NAME
-/var/usr/bin/patch -d / -p1 < ${APP_DIR}/$PATCH_NAME || do_failure
-echo "SUCCESS"
-
-# Default themes, sounds and config
 MEDIA_BASE=/media/internal/virtual-keyboard
 THEMES="themes/remix_ice themes/remix_classic themes/remix_glossy themes/LPC_Dark_Rounded_2e"
 SOUNDS=sounds/click1.wav
 
+if [ ! -e ${APP_DIR}/md5sums ]
+then
+  /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
+  echo "ERROR: md5sums file missing, aborting..."
+  exit 1
+fi
+
+while read i
+do
+  file=/`echo $i | awk -F* '{print $2}'`
+  if [ ! -e $file ]
+  then
+    echo "ERROR: Framework file cannot be found: $file"
+    echo "List of mojo builtins files:"
+    ls /usr/palm/frameworks/mojo/builtins/
+    /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
+    exit 1
+  fi
+  expected=`echo $i | awk '{print $1}'`
+  calculated=`md5sum $file | awk '{print $1}'`
+  if [ "$expected" != "$calculated" ]
+  then
+    echo "ERROR: mismatch md5sums"
+    echo "       expected: $expected"
+    echo "       calculated: $calculated"
+    /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
+    exit 1
+  fi
+done < ${APP_DIR}/md5sums
+
+for i in `/var/usr/bin/diffstat -p1 -l ${APP_DIR}/patches/add-onscreen-keyboard.patch`
+do
+  grep $i ${APP_DIR}/md5sums
+  if [ $? -ne 0 ]
+  then
+    echo "removing $i"
+    #rm -f $i
+  fi
+done
+
+cd / && /var/usr/bin/patch -p1 --dry-run < ${APP_DIR}/patches/add-onscreen-keyboard.patch
+if [ $? -ne 0 ]
+then
+  echo "ERROR: patch dryrun failed, aborting..."
+  /usr/bin/ipkg -o /var remove org.webosinternals.virtual-keyboard
+  exit 1
+fi
+
+# dry-run passed, so patch for real and create backups
+/var/usr/bin/patch -p1 -b < ${APP_DIR}/patches/add-onscreen-keyboard.patch
+
+# create md5sums of all patched files, for future removal verifications
+rm -f ${APP_DIR}/md5sums.patched
+touch ${APP_DIR}/md5sums.patched
+for i in `grep diff ${APP_DIR}/patches/add-onscreen-keyboard.patch | awk '{print $3}' | sed -e 's/.//'`
+do
+  md5sum $i >> ${APP_DIR}/md5sums.patched
+done
+
+# Default themes, sounds and config
 if [ ! -d ${MEDIA_BASE} ]
 then
   rm -rf ${MEDIA_BASE}
diff --git a/prerm b/prerm
--- a/prerm
+++ b/prerm
@@ -1,56 +1,43 @@
 #!/bin/sh
 APP_DIR=/var/usr/palm/applications/org.webosinternals.virtual-keyboard
-PATCH_NAME=add-onscreen-keyboard.patch
-FILE_LIST=`/var/usr/bin/diffstat -p1 -l $APP_DIR/$PATCH_NAME`
-PATCH_CONTROL_DIR=/var/usr/lib/.webosinternals.patches
-
-do_failure() {
-  exit 1
-}
-
-/var/usr/bin/patch -R -p1 -d / --dry-run < ${APP_DIR}/$PATCH_NAME || do_failure
-
-/var/usr/bin/patch -R -p1 -d / < ${APP_DIR}/$PATCH_NAME
-
-for i in $FILE_LIST
-do
-  file=/$i
-  orig_md5sum=`md5sum $file.webosinternals.orig | awk '{print $1}'`
-  file_md5sum=""
-
-  if [ -e $file ]
-  then
-    file_md5sum=`md5sum $file | awk '{print $1}'`
-  fi
-
-  if [ ! -e $file ] && [ ! -s $file.webosinternals.orig ] || [ "$orig_md5sum" = "$file_md5sum" ]
-  then
-    rm -f $file.webosinternals.orig
-    tmpvar=`echo $file | tr '/' '.'`
-    sed -i -e /$tmpvar/d $PATCH_CONTROL_DIR/backups
-  fi
-
-  if [ ! -e $file ] && [ ! -s $file.webosinternals.orig ]
-  then
-    rm -f $file.webosinternals.orig
-  fi
-done
-
-rm -f $PATCH_CONTROL_DIR/$PATCH_NAME
-sed -i -e /`basename $APP_DIR`/d $PATCH_CONTROL_DIR/packages
-echo "SUCCESS"
-
-# Restart Luna
-if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
-    /sbin/stop LunaSysMgr
-    /sbin/start LunaSysMgr
-fi
-
-rm -rf ${APP_DIR}/*
-
 MEDIA_BASE=/media/internal/virtual-keyboard
 THEMES="themes/remix_ice themes/remix_classic themes/remix_glossy themes/LPC_Dark_Rounded_2e"
 SOUNDS=sounds/click1.wav
+
+#cd / && /var/usr/bin/patch -p1 -R < /var/usr/palm/applications/org.webosinternals.virtual-keyboard/patches/add-onscreen-keyboard.patch
+
+if [ ! -e ${APP_DIR}/md5sums.patched ]
+then
+  echo "ERROR: No md5sums.patched file!?"
+  exit 1
+fi
+
+while read i
+do
+  file=`echo $i | awk '{print $2}'`
+  expected=`echo $i | awk '{print $1}'`
+  calculated=`md5sum $file | awk '{print $1}'`
+  if [ -e $file.orig ]
+  then
+    if [ ! -s $file.orig ]
+    then
+      rm -f $file.orig
+      rm -f $file
+    elif [ "$expected" = "$calculated" ]
+    then
+      rm -f $file
+      mv $file.orig $file
+    else
+      echo "WARNING: Failed to restore $file"
+      echo "         expected md5sum: $expected"
+      echo "         calculated md5sum: $calculated"
+      echo "         skipping..."
+    fi
+  else
+    echo "WARNING: Cannot find orig file $file.orig"
+    echo "         skipping..."
+  fi
+done < ${APP_DIR}/md5sums.patched
 
 for i in ${THEMES}
 do
@@ -62,4 +49,11 @@ do
   rm -rf ${MEDIA_BASE}/$i
 done
 
+# Restart Luna
+if [ -z "$IPKG_OFFLINE_ROOT" ]; then # Defined by recent installers that also support flags.
+    /sbin/stop LunaSysMgr
+    /sbin/start LunaSysMgr
+fi
+
+rm -rf ${APP_DIR}/*
 exit 0
